# Generated by Django 6.0.7 on 2026-07-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_create_category_and_product_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='goods.product', verbose_name='Товар')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складе',
            },
        ),
    ]
